### PR TITLE
[WIP] Refactor amendments rendering without SVG nor d3

### PR DESCRIPTION
**Pull request by njoyard**
This PR is a rewrite of #128 on the refactor-v2 branch.

It features a complete rewrite of the amendments rendering, no longer using d3 or svg. Rendering is done by AngularJS using the template, directly.

Finished :
* [x] legend tooltips and clicks
* [x] focus on a specific subject (either by click or by URL)
* [x] use 2 columns when each line of amendments is less than half display width
* [x] get rid of modules/mod2.js after ensuring that no one else uses it
* [x] restore help text on right pane
* [x] check [https compatibility](https://github.com/regardscitoyens/the-law-factory/commit/0e6f97c428f5aabb4cd48ad0f3a96c8b2b545d10)
* [x] remove bogus government code
* [x] ~~add title slug to subject classes (see [here](https://github.com/njoyard/the-law-factory/commit/0200b09daf526656d145ab90e4b4017c5653d5a5#diff-128ef7b2495e9cb0f9b5ef35c370c7e8L17) and [here](https://github.com/njoyard/the-law-factory/commit/0200b09daf526656d145ab90e4b4017c5653d5a5#diff-128ef7b2495e9cb0f9b5ef35c370c7e8L56)) and~~ restore scrolltop
* [x] restore `first-art[-s]` classes and ensure tutorial is working

Todo:
* [ ] implement a snake-like arrangement of amendments (except when using the new ordering by number since it would break its meaning then :) )
* [x] add auto-refresh (new feature)
* [ ] check that rendering is consistent across browsers
* [x] restore missing date when displaying amdt content
* [x] fix date format in amdt tooltip
* [ ] truncate article background to display a round number of squares
* [x] cross-fade amdt content (hide -> spinner -> show)
* [x] fix wrong tooltip positioning (scroll-dependent)
* [x] never use 2-column mode when grouped
* [x] keyboard navigation for amdt content
* [x] display first author in popover cf https://github.com/regardscitoyens/the-law-factory/commit/d258a24d2d0095f0a199dd964dc24100cf7e1d4c

Postponed :
* [ ] ~~rename "mod2" occurences everywhere (templates/mod2.html & setMod2Size at least)~~ *in a future PR*

Comments welcome, angularjs newbie here :P

### CODE REVIEW

**Comment by fmassot** [comment]
Now that all mod2 is in a directive, I would isolate this directive in a separate file. Maybe in modules/mod2-directive.js ?

**Comment by njoyard** [comment]
As discussed on irc, directive isolation/renaming will be done in a future PR.

Did some more work and rebased on the tip of the branch. I also updated the PR description with a to-do list. Very close to being finished \o/

**Comment by RouxRC** [comment]
Attention à l'ordering des sujets des amendements:
à ajouter à https://github.com/njoyard/the-law-factory/blob/angular-amendements-v2/public/js/directives.js#L175
cf https://github.com/njoyard/the-law-factory/commit/0200b09daf526656d145ab90e4b4017c5653d5a5#diff-128ef7b2495e9cb0f9b5ef35c370c7e8L74

**Comment by RouxRC** [comment]
Sinon pour gérer le clic sur les légendes, on utilisait un autre slug par groupe et par sort sur chaque boite d'amendement : https://github.com/njoyard/the-law-factory/commit/0200b09daf526656d145ab90e4b4017c5653d5a5#diff-128ef7b2495e9cb0f9b5ef35c370c7e8L302

On avait aussi des classes first-art et first-art-s pour les premiers de chaque, mais pas sûr de voir si et à quoi elles servaient.

**Comment by RouxRC** [comment]
and FYI, I allowed myself to add a few comments within the todo list above ;)

**Comment by njoyard** [comment]
> Attention à l'ordering des sujets des amendements

Already done here https://github.com/njoyard/the-law-factory/commit/0200b09daf526656d145ab90e4b4017c5653d5a5#diff-128ef7b2495e9cb0f9b5ef35c370c7e8L56

> Sinon pour gérer le clic sur les légendes

Legend click should do something? Does not seem to do anything on prod (or maybe not with all laws?)

**Comment by RouxRC** [comment]
- mmm indeed for the subject sorting, my bad (changed your pointer link which didn't seem correspondign though ;) )

- Yes, legends are clickable to highlight only related amendments. Are you deving on Firefox? My recalls are it was only working under chromium (which was weird by the way, see # ) but yes, it is supposed to grey all amendments except the others, explaining also the need for the click background part to deactivate any selection

**Comment by njoyard** [comment]
Okay, I'll reimplement that then.
And github is weird with links to lines of code sometimes...

**Pull request merged**
